### ISSUE TITLE
 izgled stranice(f)

### ISSUE THREAD

**Issue by dakimil** [dakimil/quiz-app#5]
Frontend: napraviti izgled početne stranice

**Comment by djordjevicnatalija** [comment]
Profesore, mala pomoc....
Uz pomoc Skeletona napravila sam izmene u tailwind.config.ts i izabrala temu, ali mam problema sa pokretanjem aplikacije (napravila sam izmene u package.json: 
"scripts": {
  "start": "svelte-kit dev",
  "build": "svelte-kit build",
  "serve": "svelte-kit preview"
}
ali ne radi)
Kada iskucam npm run dev -- --host izbacuje gresku 
![Screenshot 2024-04-20 210436](https://github.com/dakimil/quiz-app/assets/149784631/48b79bb4-826c-4bff-8a9b-c227c96b63d8)

**Comment by n-ratinac** [comment]
mislim da bi trebalo umesto `svelte-kit` da stoji `vite`. Probaj pa javi.

**Comment by djordjevicnatalija** [comment]
Pojavljuje se sad, hvala Vam
